name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn
      - run: npx nx lint org && echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
        continue-on-error: false
      - run: echo "Can't run this"