name: hello world
on: 
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
        env:
          NAME: "long"
          TODAY: $(date +'%Y-%m-%d')
      - name: Print date today
        run: echo "Hello world, today is $TODAY"
      - name: Print my name
        run: echo "Hello world, today is $NAME"