name: hello world
on: 
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: self-hosted
    steps:
        env:
          TODAY: $(date +%Y-%m-%d)
      - run: echo Hello world, today is $TODAY