name: hello world
on: 
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: My first action
        env:
          NAME: "long"
          TODAY: $(date +'%Y-%m-%d')
        run: echo "Hello world, today is $TODAY"
             echo "Hello world, today is $NAME"