name: Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - develop
      - master

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      